### ISSUE TITLE
Travis for continuous integration

### ISSUE THREAD

**Issue by daniel-j-h** [szpone/roguelike#1]
It would be great to have automated checks running for every commit your push to this repository. You can use Travis CI for that: every time you push a commit Travis will spawn up a worker which checks out your repository and runs what you specify in `.travis.yml`.

If you're not familiar with Travis check these out:

- https://docs.travis-ci.com/user/for-beginners/
- https://docs.travis-ci.com/user/getting-started/

Here are two example `.travis.yml` configurations for C++ projects:

- https://github.com/scanse/sweep-sdk/blob/master/.travis.yml
- https://github.com/daniel-j-h/cku/blob/master/.travis.yml

Tasks:
- [x] enable Travis integration for this repository
- [x] make a new pull request and add a `.travis.yml` config
- [x] in that config install g++ (and / or clang), and for all cpp files compile them
- [x] add a Travis badge to your readme showing if master builds

**Comment by szpone** [comment]
Got some errors on your travis config - https://github.com/daniel-j-h/cku/blob/master/.travis.yml The command "nix-shell --pure --run 'pushd third_party && ./build.sh && popd'" failed and exited with 1 during . ;) You might want to check that if that's not my fault.

**Comment by daniel-j-h** [comment]
Ah, the Travis config files was just an example. You don't have `nix` and we don't need it. Instead we want to install g++ and use it to compile our cpp files.
