### ISSUE TITLE
Clang-format for code formatting

### ISSUE THREAD

**Issue by daniel-j-h** [szpone/roguelike#2]
To have consistent code formatting in a project there is `clang-format` (similar to e.g. `gofmt`).

If you have the time for it it would be great if you could look into `clang-format`, install it on your machine, and give it a try! It can generate a default `.clang-format` file e.g. based on LLVM coding standards.

Tasks:
- [x] add a `.clang-format` file to this repo.
- [x] use `clang-format` and re-format all source files according to the config file

(By the way even though these issues are not directly related to C++ code I already want to get you familiar with modern toolchains and best practices - feel free to ignore if you want to focus on the language for now)

**Comment by szpone** [comment]
Done! (I hope so, after making a clang-format file I ran clang-format -i <path to file>
